"""Arquivos do Word: .docx (ZIP com XML) e .doc (formato antigo, OLE).

O .docx guarda mais historia que o PDF exportado dele:
- docProps/core.xml: autor, datas e quantas vezes foi salvo (cp:revision);
- docProps/app.xml: programa, minutos de edicao (TotalTime) e as contagens de palavras
  e caracteres que o Word atualiza a cada gravacao;
- identificadores de sessao (w:rsidR): o Word marca cada paragrafo com a sessao em que
  foi escrito. Texto digitado aos poucos tem varias sessoes; colado de uma vez, uma so;
- META-INF/*.c2pa: credencial de conteudo, quando o gerador grava uma.

O python-docx (usado pelo ChatGPT e por scripts) deixa marcas proprias: autor
"python-docx", descricao "generated by python-docx", criacao fixa em 23/12/2013 (data do
modelo dele) e contagens zeradas, porque quem as atualiza e o Word.

O .doc e lido so pelos metadados (pacote olefile, opcional): programa, datas, tempo de
edicao e macros. O texto do .doc nao e extraido.
"""

from __future__ import annotations

import io
import re
import zipfile
from datetime import datetime
from xml.etree import ElementTree

from .proveniencia import eh_manifesto, resumir_manifesto
from .texto_puro import ocultos

LIMITE_DESCOMPACTADO = 200 * 1024 * 1024  # contra "zip bomb"
DATA_MODELO_PYTHON_DOCX = "2013-12-23T23:15:00"
_W = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"
_RSID = re.compile(rb'w:rsidR="([0-9A-Fa-f]{8})"')


def _xml(z, nome):
    try:
        return ElementTree.fromstring(z.read(nome))
    except (KeyError, ElementTree.ParseError):
        return None


def _campos(raiz):
    """{nome_local: texto} dos filhos diretos (core.xml e app.xml sao planos)."""
    if raiz is None:
        return {}
    return {filho.tag.rsplit("}", 1)[-1]: (filho.text or "").strip() for filho in raiz}


def _data(valor):
    try:
        return datetime.fromisoformat(valor.replace("Z", "+00:00")) if valor else None
    except ValueError:
        return None


def _inteiro(valor):
    try:
        return int(valor)
    except (TypeError, ValueError):
        return None


def _texto_docx(raiz):
    if raiz is None:
        return ""
    paragrafos = []
    for p in raiz.iter(f"{_W}p"):
        paragrafos.append("".join(t.text or "" for t in p.iter(f"{_W}t")))
    return "\n".join(paragrafos)


def _dias(criado, modificado):
    if not (criado and modificado):
        return None
    return round(abs((modificado.replace(tzinfo=None) - criado.replace(tzinfo=None)).total_seconds()) / 86400, 2)


def inspecionar_docx(dados: bytes):
    try:
        z = zipfile.ZipFile(io.BytesIO(dados))
    except zipfile.BadZipFile as exc:
        raise ValueError("o arquivo não é um .docx válido") from exc
    nomes = z.namelist()
    if "word/document.xml" not in nomes:
        raise ValueError("o arquivo não é um documento do Word (.docx)")
    if sum(i.file_size for i in z.infolist()) > LIMITE_DESCOMPACTADO:
        raise ValueError("o .docx descompactado passa do limite de 200 MB")

    core = _campos(_xml(z, "docProps/core.xml"))
    app = _campos(_xml(z, "docProps/app.xml"))
    documento = z.read("word/document.xml")
    texto = _texto_docx(_xml(z, "word/document.xml"))
    criado, modificado = _data(core.get("created")), _data(core.get("modified"))

    marcas = " ".join((core.get("creator", ""), core.get("description", ""))).lower()
    ferramentas = []
    if "python-docx" in marcas or (criado and criado.strftime("%Y-%m-%dT%H:%M:%S") == DATA_MODELO_PYTHON_DOCX):
        ferramentas.append("biblioteca de programação (python-docx)")

    c2pa = {"presente": False}
    for nome in nomes:
        if nome.lower().endswith(".c2pa") or "c2pa" in nome.lower():
            conteudo = z.read(nome)
            if eh_manifesto(conteudo):
                c2pa = resumir_manifesto(conteudo)
                break
    escondido = ocultos(texto)
    if not c2pa["presente"]:
        c2pa = escondido["c2pa"]

    produtor = " ".join(x for x in (app.get("Application"), app.get("AppVersion")) if x)
    return {
        "formato": "docx",
        "paginas": _inteiro(app.get("Pages")),
        "paginas_sem_texto": 0,
        "texto": texto,
        "revisoes": _inteiro(core.get("revision")) or 1,
        "assinaturas": sum(1 for n in nomes if n.startswith("_xmlsignatures/") and n.endswith(".xml") and "/sig" in n),
        "produtor": produtor,
        "criador": None,  # dc:creator e o nome de uma pessoa: nao vai para o relatorio
        "ferramentas_edicao": ferramentas,
        "criado_em": criado.isoformat() if criado else None,
        "modificado_em": modificado.isoformat() if modificado else None,
        "dias_entre_criacao_e_modificacao": _dias(criado, modificado),
        "tempo_edicao_min": _inteiro(app.get("TotalTime")),
        "sessoes_edicao": len(set(_RSID.findall(documento))),
        "palavras_registradas": _inteiro(app.get("Words")),
        # O app.xml do python-docx diz "Microsoft Macintosh Word": nao conta como Word de verdade.
        "eh_word": "microsoft" in produtor.lower() and "word" in produtor.lower() and not ferramentas,
        "caracteres_invisiveis": escondido["caracteres_invisiveis"],
        "elementos_ativos": ["macros (VBA)"] if any(n.lower().endswith("vbaproject.bin") for n in nomes) else [],
        "c2pa": c2pa,
    }


def inspecionar_doc(dados: bytes):
    base = {
        "formato": "doc", "paginas": None, "paginas_sem_texto": 0, "texto": "", "revisoes": None,
        "assinaturas": 0, "produtor": "", "criador": None, "ferramentas_edicao": [], "criado_em": None,
        "modificado_em": None, "dias_entre_criacao_e_modificacao": None, "tempo_edicao_min": None,
        "elementos_ativos": [], "c2pa": {"presente": False}, "metadados_lidos": False,
    }
    try:
        import olefile
    except ImportError:
        return base
    try:
        ole = olefile.OleFileIO(io.BytesIO(dados))
        meta = ole.get_metadata()
    except Exception as exc:  # OLE corrompido
        raise ValueError("o arquivo não é um .doc válido") from exc

    def texto(valor):
        return valor.decode("latin-1", "replace").strip() if isinstance(valor, bytes) else (valor or "")

    criado, modificado = meta.create_time, meta.last_saved_time
    tempo = meta.total_edit_time  # olefile devolve segundos
    macros = ole.exists("Macros") or ole.exists("_VBA_PROJECT_CUR")
    ole.close()
    return {
        **base,
        "paginas": meta.num_pages or None,
        "revisoes": _inteiro(texto(meta.revision_number)) or None,
        "produtor": texto(meta.creating_application),
        "criado_em": criado.isoformat() if criado else None,
        "modificado_em": modificado.isoformat() if modificado else None,
        "dias_entre_criacao_e_modificacao": _dias(criado, modificado),
        "tempo_edicao_min": round(tempo / 60) if isinstance(tempo, (int, float)) else None,
        "elementos_ativos": ["macros (VBA)"] if macros else [],
        "metadados_lidos": True,
    }
